<h1>Teoria de Grafos</h1>

Los grafos son estructuras discretas que consisten de vértices y
aristas que conectan los vértices. Existen disintos tipos de grafos,
dependiendo si las aristas tienen o no dirección, si existen múltiples
aristas para un mismo vértices o si se permiten o no lazos.

Un grafo es una tupla $G = (V , E )$ donde $V$ es un conjunto (finito o
infinito) de vértices y E es un cuna colección finita de aristas. El
conjunto E contiene elementos de la unión de todos los subconjuntos con
uno o dos elementos del conjunto $V$ . Esto quiere decir, que cada
elemento de E es un subconjunto de uno o dos elementos de $V$ .



In [2]:
import numpy as np

class abstract_graph:
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges} | {v for u,v in self.edges}
        
    def adjacency_matrix(self):
        pass
    
    def adjacency_list(self):
        pass

Un grafo simple es un grafo en el cual existe sólo una arista $(u, v)$ para
conectar dos vértices $u$ y $v$ .

In [28]:
class simple_graph(abstract_graph):
    
    def __init__(self,_edges):
        tmp=[]
        for (u,v) in _edges:
            if (v,u) not in tmp:
                tmp.append((u,v))
        self.edges=tmp
        self.nodes={u for u,v in _edges} | {v for u,v in _edges}
     
    def adjacency_matrix(self):
        # completar
        n=len(self.nodes)
        mat=np.zeros((n,n))
        for i,v in enumerate(self.nodes):
            for j,k in enumerate(self.nodes):
                if (v,k) in self.edges:
                    mat[i,j]=1
                    mat[j,i]=1
        return mat
    
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges if u==n } | {u for u,v in self.edges if v==n}
        return {v:adjacent(v) for v in self.nodes}
        
    

E={('A','B'),('C','D'),('B','D'),('B','A')}
G=simple_graph(E)
print 'aristas',G.edges
print 'nodos : ',G.nodes
print 'matriz adyacencia : ',G.adjacency_matrix()
print 'lista adyacencia : ',G.adjacency_list()

aristas [('B', 'A'), ('C', 'D'), ('B', 'D')]
nodos :  set(['A', 'C', 'B', 'D'])
matriz adyacencia :  [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]
lista adyacencia :  {'A': set(['B']), 'C': set(['D']), 'B': set(['A', 'D']), 'D': set(['C', 'B'])}


In [29]:
a={'A','C','B'}

for n,v in enumerate(a):
    print n,v
    
    

0 A
1 C
2 B


Un multi-grafo simple es un grafo en el cual existe más de una arista
$(u, v)$ para conectar dos vértices $u$ y $v$ (aristas paralelas y lazos).

In [14]:
class multi_graph(abstract_graph):
        
    def adjacency_matrix(self):
        # completar
        n=len(self.nodes)
        mat=np.zeros((n,n))
        for i,v in enumerate(self.nodes):
            for j,k in enumerate(self.nodes):
                if (v,k) in self.edges:
                    mat[i,j]=1
                    mat[j,i]=1
        return mat
    
    def adjacency_list(self):
        # completar
        pass
    
E2=[(1,2),(3,4),(2,4),(1,2),(1,1)]
G2=multi_graph(E2)
print 'nodos : ',G2.nodes
print 'matriz adyacencia : ',G2.adjacency_matrix()
print 'lista adyacencia : ',G2.adjacency_list()

nodos :  set([1, 2, 3, 4])
matriz adyacencia :  None
lista adyacencia :  None


Un grafo dirigido es un grafo en el cual cada arista $(u,v)$ consiste en un
par ordenado de vértices $u$ y $v$.

In [4]:
class multi_digraph(abstract_graph):
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges} | {u for u,v in self.edges}

        
    def adjacency_matrix(self):
        # completar
        pass
    
    def adjacency_list(self):
        # completar
        pass
    

E3=[(1,2),(3,4),(2,4),(2,1),(2,1)]
G3=multi_digraph(E3)
print 'nodos : ',G3.nodes
print G3.adjacency_matrix()
print 'lista adyacencia : ',G3.adjacency_list()

nodos :  set([1, 2, 3])
None
lista adyacencia :  None


In [7]:
class simple_weighted_graph(abstract_graph):
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges.keys()} | {v for u,v in self.edges.keys()}
        
    def adjacency_matrix(self):
        # completar
        n=len(self.nodes)
        mat=np.zeros((n,n))
        return mat
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges.keys() if u==n } | {u for u,v in self.edges.keys() if v==n}
        return {v:adjacent(v) for v in self.nodes}
        
 

In [9]:
E4={(1,2):1,(3,4):2,(2,4):1}
G4=simple_weighted_graph(E4)
print 'nodos : ',G4.nodes
print G4.adjacency_matrix()
print 'lista adyacencia : ',G4.adjacency_list()

nodos :  set([1, 2, 3, 4])
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
lista adyacencia :  {1: set([2]), 2: set([1, 4]), 3: set([4]), 4: set([2, 3])}
