<h1>Recorrido de Grafos</h1>

Dado un grafo ponderado $(G , w )$ donde $G = (V , E )$ y $w : E  \mapsto \mathbb R$, un
arbol de expansión mı́nima es un arbol de expansión en el que la suma
de los pesos w de las aristas es mı́nima.

<h2>Algoritmo Prim</h2>

El algoritmo de Prim construye un arbol visitando vértices de
manera iterativa hasta que se obtiene un árbol de expansión mı́nima.Se comienza desde un vértice cualquiera y en cada iteración se agrega la arista que tenga el mı́nimo peso y no complete un ciclo.
La complejidad computacional del algoritmo de Prim es $O(V \operatorname{log} V)$.
El siguiente pseudo-código implementa el algoritmo mediante una cola de prioridad:


<img src="images/algoritmo_prim.png" />

<h2>Algoritmo Kruskal</h2>

El algoritmo de Kruskal construye un arbol visitando aristas de
manera iterativa hasta que se obtiene un árbol de expansión mı́nima.
Se comienza desde un vértice cualquiera y en cada iteración se
agrega la arista que tenga el mı́nimo peso y no complete un ciclo.
La complejidad computacional del algoritmo de Kruskal es $O(E \operatorname{log} E)$.


<img src="images/algoritmo_kruskal.png" />

In [1]:
import numpy as np
from heapq import heappush,heappop

class abstract_graph:
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges} | {u for u,v in self.edges}
        
    def adjacency_matrix(self):
        pass
    
    def adjacency_list(self):
        pass


class weighted_graph(abstract_graph):
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges.keys()} | {v for u,v in self.edges.keys()}
        
    def adjacency_matrix(self):
        n=len(self.nodes)
        mat=np.zeros((n,n))
        adjacent=lambda x : [1 if x==v else 0 for (u,v) in enumerate(sorted(list(G.nodes))) ]
        L=self.adjacency_list()
        i=0
        for v in sorted(list(G.nodes)):
            for l in L[v]:
                mat[i,]+=adjacent(l)
            i=i+1
        return mat
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges.keys() if u==n } | {u for u,v in self.edges if v==n}
        return {v:adjacent(v) for v in self.nodes}
    
    def prim_mst(self,start):
        path_cost=0
        self.open=[]
        self.closed=[start]
        tree=[]
        adjacency=self.adjacency_list()
        parent={}
        while len(self.closed)<len(G.nodes):
            for v in adjacency[start]:
                priority =  self.edges[(start,v)] if self.edges.has_key((start,v)) else self.edges[(v,start)] 
                if not parent.has_key(v):
                    parent.update({v:(priority,start)})
                else:
                    w,u=parent[v]
                    if priority < w:
                        parent.update({v:(priority,start)})
                heappush(self.open, (priority, v))
            while True:
                p,v=heappop(self.open)
                if self.closed.count(v)==0:
                    w,u=parent[v]
                    tree.append((u,v))
                    break
            path_cost=path_cost+p
            start=v
            self.closed.append(v)
        return tree,path_cost

    def kruskal_mst(self):
        #completar
        pass

In [2]:
E={('a','b'):4,('a','h'):8,('b','h'):11,('b','c'):8,('c','d'):7,
   ('h','i'):7,('i','c'):2,('h','g'):1,('g','f'):2,('c','f'):4,
   ('d','e'):9,('d','f'):14,('f','e'):10}
G=weighted_graph(E)
print 'nodos : ',G.nodes
print 'matriz adyacencia : ',G.adjacency_matrix()
print 'lista adyacencia : ',G.adjacency_list()
print 'Arbol Recubridor : ',G.prim_mst('a')

nodos :  set(['a', 'c', 'b', 'e', 'd', 'g', 'f', 'i', 'h'])
matriz adyacencia :  [[ 0.  1.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  0.  0.  0.]
 [ 0.  0.  1.  1.  1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  0.]
 [ 1.  1.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.  0.]]
lista adyacencia :  {'a': set(['h', 'b']), 'c': set(['i', 'b', 'd', 'f']), 'b': set(['a', 'h', 'c']), 'e': set(['d', 'f']), 'd': set(['c', 'e', 'f']), 'g': set(['h', 'f']), 'f': set(['c', 'e', 'd', 'g']), 'i': set(['h', 'c']), 'h': set(['i', 'a', 'b', 'g'])}
Arbol Recubridor :  ([('a', 'b'), ('b', 'c'), ('c', 'i'), ('c', 'f'), ('f', 'g'), ('g', 'h'), ('c', 'd'), ('d', 'e')], 37)


<h2>Ejercicio</h2>

Se desea construir un acueducto que una las ciudades de Mafil, Valdivia, Corral, Paillaco y Los Lagos. El costo en miles de millones de pesos viene dado en la siguiente tabla:

<table>
    <tr><td></td><td>Mafil</td><td>Valdivia</td><td>Corral</td><td>Los Lagos</td></tr>
    <tr><td>Valdivia</td><td>7</td><td></td><td></td><td></td></tr>
    <tr><td>Corral</td><td>19</td><td>6</td><td></td><td></td></tr>
    <tr><td>Los Lagos</td><td>5</td><td>17</td><td>9</td><td></td></tr>
    <tr><td>Paillaco</td><td>13</td><td>5</td><td>7</td><td>14</td></tr>
</table>

¿Qué tramos debieran construirse para gastar la menor cantidad posible de dinero?