<h1>Recorrido de Grafos</h1>

Dado un grafo ponderado $(G , w )$ donde $G = (V , E )$ y $w : E  \mapsto \mathbb R$, un
arbol de expansión mı́nima es un arbol de expansión en el que la suma
de los pesos w de las aristas es mı́nima.

<h2>Algoritmo Prim</h2>

El algoritmo de Prim construye un arbol visitando vértices de
manera iterativa hasta que se obtiene un árbol de expansión mı́nima.Se comienza desde un vértice cualquiera y en cada iteración se agrega la arista que tenga el mı́nimo peso y no complete un ciclo.
La complejidad computacional del algoritmo de Prim es $O(V \operatorname{log} V)$.
El siguiente pseudo-código implementa el algoritmo mediante una cola de prioridad:


<img src="images/algoritmo_prim.png" />

<h2>Algoritmo Kruskal</h2>

El algoritmo de Kruskal construye un arbol visitando aristas de
manera iterativa hasta que se obtiene un árbol de expansión mı́nima.
Se comienza desde un vértice cualquiera y en cada iteración se
agrega la arista que tenga el mı́nimo peso y no complete un ciclo.
La complejidad computacional del algoritmo de Kruskal es $O(E \operatorname{log} E)$.


<img src="images/algoritmo_kruskal.png" />

In [6]:
import numpy as np
from heapq import heappush,heappop

class abstract_graph:
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges} | {v for u,v in self.edges}
        
    def adjacency_matrix(self):
        pass
    
    def adjacency_list(self):
        pass

    
class simple_graph(abstract_graph):
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges if u==n } | {u for u,v in self.edges if v==n}
        return {v:adjacent(v) for v in self.nodes}
    

    
class weighted_graph(abstract_graph):
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges.keys()} | {v for u,v in self.edges.keys()}
        
    def adjacency_matrix(self):
        n=len(self.nodes)
        mat=np.zeros((n,n))
        adjacent=lambda x : [1 if x==v else 0 for (u,v) in enumerate(sorted(list(G.nodes))) ]
        L=self.adjacency_list()
        i=0
        for v in sorted(list(G.nodes)):
            for l in L[v]:
                mat[i,]+=adjacent(l)
            i=i+1
        return mat
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges.keys() if u==n } | {u for u,v in self.edges if v==n}
        return {v:adjacent(v) for v in self.nodes}
    
    
    


In [8]:
def depth_first_search(graph,start):
    stack, path = [start], []
    adjacency=graph.adjacency_list()
    while stack:
        vertex = stack.pop()
        if vertex in path:
            continue
        path.append(vertex)
        for neighbor in adjacency[vertex]:
            stack.append(neighbor)
    return path

In [10]:
E={('a','b'):4,('a','h'):8,('b','h'):11,('b','c'):8,('c','d'):7,
   ('h','i'):7,('i','c'):2,('h','g'):1,('g','f'):2,('c','f'):4,
   ('d','e'):9,('d','f'):14,('f','e'):10}
G=weighted_graph(E)
print('nodos : ',G.nodes)
print('matriz adyacencia : ',G.adjacency_matrix())
print('lista adyacencia : ',G.adjacency_list())


nodos :  {'f', 'h', 'a', 'e', 'i', 'b', 'c', 'd', 'g'}
matriz adyacencia :  [[0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0.]]
lista adyacencia :  {'f': {'g', 'd', 'c', 'e'}, 'h': {'i', 'g', 'b', 'a'}, 'a': {'b', 'h'}, 'e': {'f', 'd'}, 'i': {'h', 'c'}, 'b': {'c', 'h', 'a'}, 'c': {'f', 'd', 'i', 'b'}, 'd': {'f', 'c', 'e'}, 'g': {'f', 'h'}}


In [12]:
E={(1,2),(1,3),(2,4),(3,5),(2,5),(4,6),(5,6),(6,7)}
G=simple_graph(E)
print('nodos : ',G.nodes)
print(G.adjacency_list())

dfs_path=depth_first_search(G,1)
print(dfs_path)

nodos :  {1, 2, 3, 4, 5, 6, 7}
{1: {2, 3}, 2: {1, 4, 5}, 3: {1, 5}, 4: {2, 6}, 5: {2, 3, 6}, 6: {4, 5, 7}, 7: {6}}
[1, 3, 5, 6, 7, 4, 2]


<h2>Ejercicio</h2>

Se desea construir un acueducto que una las ciudades de la region del Maule. El costo en distancia se encuentra en mm en un archivo csv.

In [13]:
import pandas as pd

df=pd.read_csv('data/distancias_maule.csv', encoding = 'utf-8',dtype={'WKT':str,'InputID':str,'TargetID':str,'Distance':float}) 

df.loc[df['InputID']=='TALCA'].head()

WKT InputID      TargetID  \
0  MULTIPOINT ((-71.661999 -35.432349),(-71.59687...   TALCA    PANGUILEMO   
1  MULTIPOINT ((-71.661999 -35.432349),(-71.56431...   TALCA   HUILQUILEMU   
2  MULTIPOINT ((-72.412391 -35.335426),(-71.66199...   TALCA  CONSTITUCION   
3  MULTIPOINT ((-72.333641 -35.427048),(-71.66199...   TALCA    SANTA OLGA   
4  MULTIPOINT ((-72.494926 -35.469452),(-71.66199...   TALCA  LOS PELLINES   

       Distance  
0   9402.992976  
1   9026.792210  
2  69023.063640  
3  60993.437978  
4  75728.660537

In [14]:
df['WKT'] = df['WKT'].apply(lambda x: x.encode('ascii', 'ignore').decode('ascii'))
df['InputID'] = df['InputID'].apply(lambda x: x.encode('ascii', 'ignore').decode('ascii'))
df['TargetID'] = df['TargetID'].apply(lambda x: x.encode('ascii', 'ignore').decode('ascii'))
df['InputID'].unique()

array(['TALCA', 'PANGUILEMO', 'HUILQUILEMU', 'CONSTITUCION', 'SANTA OLGA',
       'LOS PELLINES', 'CUREPTO', 'EMPEDRADO', 'MAULE', 'CULENAR',
       'VILLA FRANCIA', 'CHACARILLAS', 'PELARCO', 'PENCAHUE', 'CUMPEO',
       'SAN CLEMENTE', 'SAN RAFAEL', 'CAUQUENES', 'CHANCO', 'PELLUHUE',
       'QUILICURA', 'CURICO', 'SARMIENTO', 'VILLA LOS NICHES',
       'SAN ALBERTO', 'HUALAE', 'LICANTEN', 'ILOCA', 'MOLINA',
       'ITAHUE UNO', 'RAUCO', 'ROMERAL', 'SAGRADA  FAMILIA', 'VILLA PRAT',
       'TENO', 'LLICO', 'LAGO VICHUQUEN', 'LINARES', 'VARA GRUESA',
       'LAS OBRAS', 'COLBUN', 'PANIMAVIDA', 'LONGAVI', 'PARRAL', 'RETIRO',
       'COPIHUE', 'SAN JAVIER', 'BOBADILLA', 'VILLA ALEGRE',
       'YERBAS BUENAS'], dtype=object)

In [15]:
E={}
for index, row in df.iterrows():
    E.update({(str(row['InputID']), str(row['TargetID'])):row['Distance']/1000})

In [16]:
from matplotlib import pyplot
from shapely.geometry import MultiPoint
from shapely import wkt

points=[]
for index, row in df.iterrows():
    points.append(wkt.loads(str(row['WKT'])))