<h1>Recorrido de Grafos</h1>

Dado un grafo ponderado $(G , w )$ donde $G = (V , E )$ y $w : E  \mapsto \mathbb R$, un
arbol de expansión mı́nima es un arbol de expansión en el que la suma
de los pesos w de las aristas es mı́nima.

In [16]:
import numpy as np

class abstract_graph:
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges} | {u for u,v in self.edges}
        
    def adjacency_matrix(self):
        pass
    
    def adjacency_list(self):
        pass


class simple_weighted_graph(abstract_graph):
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges.keys()} | {v for u,v in self.edges.keys()}
        
    def adjacency_matrix(self):
        # completar
        n=len(self.nodes)
        mat=np.zeros((n,n))
        return mat
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges.keys() if u==n } | {u for u,v in self.edges.keys() if v==n}
        return {v:adjacent(v) for v in self.nodes}
    
    def prim_mst(self):
        #completar
        pass

    def kruskal_mst(self):
        #completar
        pass

In [15]:
E={('a','b'):1,('c','d'):2,('b','c'):1}
G=simple_weighted_graph(E)
L=list(G.nodes)
print 'nodos : ', L
print G.adjacency_matrix()
print 'lista adyacencia : ',G.adjacency_list()

nodos :  ['a', 'c', 'b', 'd']
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
lista adyacencia :  {'a': set(['b']), 'c': set(['b', 'd']), 'b': set(['a', 'c']), 'd': set(['c'])}
